@localhost=localhost:4004/odata/v4/main
@id=496accfc-b34f-4f7c-ade3-1d44aef2136e
@customerId=21fcb526-3de7-4ff6-9978-d36cf6647470
@productId=873a4955-c800-4be8-9a0e-6885ebdf990b



GET http://{{localhost}}/SalesOrderHearder
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHearder
Content-Type: application/json

{"id": "{{id}}",
"customer_id": "{{customerId}}",
"totalAmount": 4.98,
"items": [
    {
        "id": "f8d912e8-ff1e-4c13-8f64-6f9dba9d2fa8",
        "header_id": "{{id}}",
        "product_id": "{{productId}}",
        "quantity": 10,
        "price": 2.99
    },
    {
        "id": "a7da4135-9a26-4960-a7e5-3daa970131cb",
        "header_id": "{{id}}",
        "product_id": "{{productId}}",
        "quantity": 5,
        "price": 1.99
    }
]
}

###
DELETE  http://{{localhost}}/SalesOrderHearder(id={{id}})
Content-Type: application/json

###
PUT  http://{{localhost}}/SalesOrderHearder(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "teste"
}


###
# Buscar todos os pedidos maiores ou iguais a 2 milhoes
GET http://{{localhost}}/SalesOrderHearder?$filter=totalAmount ge 2000000
Content-Type: application/json

###
# Buscar todos os pedidos menores ou iguais a 200k
GET http://{{localhost}}/SalesOrderHearder?$filter=totalAmount le 200000
Content-Type: application/json


###
# Expandindo os items, produtos e customers
GET http://{{localhost}}/SalesOrderHearder?$expand=items($expand=product),customer
Content-Type: application/json

###
# Expandindo os items, produtos e customers e filtrando
GET http://{{localhost}}/SalesOrderHearder?$expand=items($expand=product;$filter=quantity le 46),customer
Content-Type: application/json


###
# Selecionar somente customer e id do Sales Order Header
GET http://{{localhost}}/SalesOrderHearder?$select=customer&$expand=customer($select=email)
Content-Type: application/json