@localhost=localhost:4004/odata/v4/main



GET http://{{localhost}}/SalesOrderHearder
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHearder
Content-Type: application/json

{}

###
DELETE  http://{{localhost}}/SalesOrderHearder(1234)
Content-Type: application/json

###
PUT  http://{{localhost}}/SalesOrderHearder(id=2a1e9829-8cb3-4608-83fe-7eba9224c97c)
Content-Type: application/json

{
    "modifiedBy": "teste"
}