@localhost=localhost:4004/odata/v4/main
@id=1493082a-9128-4973-892f-550b1ca747f0
@customerId=15968623-5b27-46d2-a8a6-1389bb63601b
#produto sem estoque
@productId1=42232154-0d3f-491a-a2d0-8314ce46fd4d
@productId2=12280032-442c-4afe-b7a5-64b1a4d35d45


GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic gilvan1:Gs@123456

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic gilvan:Gs@123456

{"id": "{{id}}",
"customer_id": "{{customerId}}",
"items": [
    {
        "id": "f8d912e8-ff1e-4c13-8f64-6f9dba9d2fa9",
        "header_id": "{{id}}",
        "product_id": "{{productId2}}",
        "quantity": 10,
        "price": 1000
    },
    {
        "id": "a7da4135-9a26-4960-a7e5-3daa970131cc",
        "header_id": "{{id}}",
        "product_id": "{{productId2}}",
        "quantity": 5,
        "price": 5000
    }
]
}

###
DELETE  http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic gilvan:Gs@123456

###
PUT  http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic gilvan1:123456

{
    "modifiedBy": "teste"
}


###
# Buscar todos os pedidos maiores ou iguais a 2 milhoes
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json
Authorization: Basic gilvan1:123456

###
# Buscar todos os pedidos menores ou iguais a 200k
GET http://{{localhost}}/SalesOrderHeader?$filter=totalAmount le 200000
Content-Type: application/json
Authorization: Basic gilvan1:123456

###
# Expandindo os items, produtos e customers
GET http://{{localhost}}/SalesOrderHeader?$expand=items($expand=product),customer
Content-Type: application/json
Authorization: Basic gilvan1:123456
###
# Expandindo os items, produtos e customers e filtrando
GET http://{{localhost}}/SalesOrderHeader?$expand=items($expand=product;$filter=quantity le 46),customer
Content-Type: application/json
Authorization: Basic gilvan1:123456

###
# Selecionar somente customer e id do Sales Order Header
GET http://{{localhost}}/SalesOrderHeader?$select=customer&$expand=customer($select=email)
Content-Type: application/json
Authorization: Basic gilvan1:123456
###
# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeader/$count
Content-Type: application/json
Authorization: Basic gilvan1:123456
###
# Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=5&$top=2
Content-Type: application/json
Authorization: Basic gilvan1:123456
###
# Buscando dados com $search
GET http://{{localhost}}/SalesOrderHeaders?$search=w02k
Content-Type: application/json
Authorization: Basic gilvan1:123456
